name: CD Staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy:
    name: Redeploy to Staging EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Set up SSH key and connect to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ec2-65-0-134-177.ap-south-1.compute.amazonaws.com
          EC2_USER: ubuntu

        run: |
          echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa_ec2
          chmod 600 ~/.ssh/id_rsa_ec2
          ssh -i ~/.ssh/id_rsa_ec2 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USER@$EC2_HOST '
            echo "Successfully connected to EC2 instance!"
            # --- START: Deployment Commands ---
            cd monodep/
            git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
            echo "Deployment commands finished."
            # --- END: Deployment Commands ---
          '
          rm -f ~/.ssh/id_rsa_ec2
